apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  # selector: 
  #   matchLabels:
  #     app: drupal-mysql-pod
  template:
    metadata:
      name: drupal-mysql-pod
      labels:
        app: drupal-mysql-pod
    spec:
      containers: 
      - name: drupal-mysql-pod
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/mysql
          subPath: dbdata
          name: mypd
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-secret
              key: MYSQL_USER
      volumes:
      - name: mypd
        persistentVolumeClaim:
          claimName: drupal-mysql-pvc
      
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
  # labels:
  #   app: drupal-mysql
spec:
  selector: 
    app: drupal-mysql-pod
  ports: 
  - port: 3306
