apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-secret
stringData:
  MYSQL_ROOT_PASSWORD: root_password #cm9vdF9wYXNzd29yZA==
  MYSQL_DATABASE:  drupal-database  #ZHJ1cGFsLWRhdGFiYXNl
  MYSQL_USER: root #cm9vdA==
  