apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-volume
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/volume/nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: logger
    image: nginx:alpine
    volumeMounts:
    - name: mypd
      mountPath: /var/www/nginx
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: log-claim







