apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis 
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeName: controlplane
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   # operator: Exists
      #   effect: NoSchedule
      # # nodeSelector:
      # #   label: master   
      # affinity: 
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - controlplane
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          # limits:
          #   cpu: "0.2"
          requests:
            cpu: "0.2"
        volumeMounts:
        - name: data
          mountPath: /redis-master-data
        - name: redis-config
          mountPath: /redis-master
      volumes:
      - name: data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-config