apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-busybox
  name: my-busybox
  namespace: dev2406
spec:
  nodeName: controlplane
  containers:
  - image: busybox
    name: secret
    command: ["/bin/sh", "-c", "sleep 3600"]
    # command:
    # - sleep
    # - 3600
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret-volume
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: dotfile-secret
