# create secret generic <secret-name> --from-literal=DB_Host=mysql
# create secret generic <secret-name> --from-file=app_secret.properties
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  DB_Password: abcd
# data:
#   DB_Password: Xc=a => base64encoded


# echo -n "bxlzcWw=" | base64 --decode