# create configmap app-config --from-literal=APP_COLOR=blue --from-literal=APP_MODE=prod
# create configmap app-config --from-file=app_config.properties

# get cm

# explain pods --recursive | grep envFrom -A3

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod