apiVersion: batch/v1
kind: Job
metadata:
  name: match-add-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ['expr', '3','+','2']
        args: ["HOSTNAME", "KUBERNETES_PORT"]
      restartPolicy: Never 
    
  