apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reporting-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
          - name: math-add
            image: ubuntu
            command: ['expr', '3','+','2']
            args: ["HOSTNAME", "KUBERNETES_PORT"]
          restartPolicy: Never 
    
    # watch "kubectl get pods"
  