apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
spec:
  selector: 
    matchLabels:
      app: redis-container
  template:
    metadata:
      name: redis
      labels:
        app: redis-container
    spec:
      containers:
      - name: redis
        image: redis:alpine
        volumeMounts:
        - mountPath: /data
          name: redis-data
        ports: 
        - containerPort: 6379
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vote
spec:
  selector: 
    app: redis-container
  ports:
  - port: 6379
    targetPort: 6379