apiVersion: v1
data:
  DB_NAME: "SQL3322"
  DB_HOST: "sql322.mycompany.com"
  DB_PORT: "3306"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-16T09:27:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:DB_NAME: {}
    manager: kubectl-create
    operation: Update
    time: "2021-02-16T09:27:35Z"
  name: cm-3392845
  namespace: default
  resourceVersion: "5924"
  selfLink: /api/v1/namespaces/default/configmaps/cm-3392845
  uid: 2293b904-9791-429e-ae79-76e34d23a205