apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  namespace: development
  labels:
    run: jekyll
spec:
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    volumeMounts:
    - mountPath: /site
      name: site
    command:  [ "jekyll", "new", "/site" ] 
    # args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
  containers: 
  - name: jekyll
    image: kodekloud/jekyll-serve
    volumeMounts:
    - mountPath: /site
      name: site
  volumes:
  - name: site
    persistentVolumeClaim:
      claimName: jekyll-site
---
apiVersion: v1
kind: Service
metadata:
  name: jekyll
  namespace: development
spec:
  type: NodePort
  selector: 
    run: jekyll
  ports:
  - port: 8080
    targetPort: 4000
    nodePort: 30097
