apiVersion: v1
kind: Pod
metadata:
  name: gop-fileserver
spec:
  containers: 
  - name: gop-fileserver
    image: kodekloud/fileserver
    volumeMounts:
    - mountPath: /web
      name: data-store
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
      
---
apiVersion: v1
kind: Service
metadata:
  name: gop-fs-service
spec:
  selector: 
    app: gop-fileserver
  type: NodePort
  ports: 
  - port: 8080
    targetPort: 8080
    nodePort: 31200
